# O Brummy usa Plymouth: o hook precisa entrar depois do udev.
---
hooks:
  - base
  - udev
  - plymouth
  - autodetect
  - microcode
  - modconf
  - kms
  - keyboard
  - keymap
  - consolefont
  - block
  - filesystems
  - fsck
