# Depois de copiar o live para o disco, tira o que só fazia sentido no live.
---
backend: pacman
skip_if_no_internet: true
update_db: false
update_system: false

operations:
  - remove:
      - calamares
      - archiso
      - mkinitcpio-archiso
      - memtest86+
      - memtest86+-efi
      - edk2-shell
