---
services:
  - name: greetd
    mandatory: false
  - name: NetworkManager
    mandatory: false
  - name: libvirtd
    mandatory: false
  - name: bluetooth
    mandatory: false

disable:
  - name: brummy-live-setup
    mandatory: false
