# Copia o sistema live para o disco.
# O caminho depende do install_dir do profiledef.sh (install_dir="brummy").
---
unpack:
  - source: "/run/archiso/bootmnt/brummy/x86_64/airootfs.sfs"
    sourcefs: "squashfs"
    destination: ""
