---
defaultGroups:
  - name: wheel
  - name: video
  - name: audio
  - name: input
  - name: storage
  - name: network
  - name: libvirt
  - name: kvm
  - name: docker
    must_exist: false

autologinGroup: autologin
doAutologin: false

# Jeito Arch: sem senha de root, tudo por sudo (o grupo wheel já tem).
setRootPassword: false

sudoersGroup: wheel
setupGroups: true

userShell: /bin/bash

passwordRequirementsWeak: false
allowWeakPasswords: false
allowWeakPasswordsDefault: false
