# Brummy — ThinkPad T430: LVDS 1366x768 (comum) ou 1600x900 (HD+)
# Se o seu T430 for HD+ (1600x900), troque a primeira linha.
# HDMI/VGA externo sobe automático pelo fallback.
monitor = eDP-1, 1366x768@60, 0x0, 1
# monitor = eDP-1, 1600x900@60, 0x0, 1
monitor = , preferred, auto, 1
