# Brummy — GTK3 escuro de verdade (WhiteSur-Dark + ícones WhiteSur + Bibata)
[Settings]
gtk-theme-name=WhiteSur-Dark
gtk-icon-theme-name=WhiteSur
gtk-cursor-theme-name=Bibata-Modern-Ice
gtk-cursor-theme-size=28
gtk-font-name=Inter 11
gtk-application-prefer-dark-theme=1
gtk-enable-animations=1
gtk-xft-antialias=1
gtk-xft-hinting=1
gtk-xft-hintstyle=hintslight
gtk-xft-rgba=rgb
